name: driver
description: "A new Flutter project."
publish_to: 'none'

version: 7.0.0+20

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  country_code_picker: ^3.2.0
  crypto: ^3.0.6
  dotted_border: ^3.0.1
  geocoding: ^4.0.0
  googleapis_auth: ^2.0.0
  cached_network_image: ^3.4.1
  flutter_easyloading: ^3.0.5
  flutter_email_sender: ^8.0.0
  flutter_html: any
  flutter_local_notifications: ^19.2.1
  flutter_svg: ^2.0.17
  location: ^8.0.0
  get: ^4.7.2
  google_maps_flutter: ^2.10.1
  google_sign_in: ^7.2.0
  image_picker: ^1.1.2
  intl: ^0.20.2
  pin_code_fields: ^8.0.1
  provider: ^6.1.2
  qr_flutter: ^4.1.0
  shared_preferences: ^2.5.2
  sign_in_with_apple: ^7.0.1
  syncfusion_flutter_datepicker: ^31.2.5
  timer_count_down: ^2.2.2
  url_launcher: ^6.3.1
  uuid: ^4.5.1
  date_picker_timeline: ^1.2.6
  flutter_rating_bar: ^4.0.1
  flutter_polyline_points: ^3.0.1
  clipboard: ^2.0.2
  map_launcher: ^4.0.0
  timelines_plus: ^1.0.6
  in_app_review: ^2.0.10
  share_plus: ^12.0.1
  mailer: ^6.4.1
  photo_view: ^0.15.0
  path_provider: ^2.1.5
  path: ^1.9.1
  video_compress: ^3.1.4
  video_player: ^2.9.3
  audioplayers: ^6.2.0
  flutter_map: ^8.2.1
  latlong2: ^0.9.1
  flutter_stripe: ^12.1.0
  razorpay_flutter: ^1.4.0
  flutter_paypal: ^0.2.1
  http: ^1.5.0
  geolocator: ^14.0.2
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  firebase_messaging: ^16.0.4
  firebase_storage: ^13.0.4
  firebase_database: ^12.0.4
  cloud_firestore: ^6.1.0
  firebase_app_check: ^0.4.1+2

dependency_overrides:
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Urbanist-Black
      fonts:
        - asset: assets/fonts/Urbanist-Black.ttf
    - family: Urbanist-Bold
      fonts:
        - asset: assets/fonts/Urbanist-Bold.ttf
    - family: Urbanist-ExtraBold
      fonts:
        - asset: assets/fonts/Urbanist-ExtraBold.ttf
    - family: Urbanist-ExtraLight
      fonts:
        - asset: assets/fonts/Urbanist-ExtraLight.ttf
    - family: Urbanist-Light
      fonts:
        - asset: assets/fonts/Urbanist-Light.ttf
    - family: Urbanist-Medium
      fonts:
        - asset: assets/fonts/Urbanist-Medium.ttf
    - family: Urbanist-Regular
      fonts:
        - asset: assets/fonts/Urbanist-Regular.ttf
    - family: Urbanist-SemiBold
      fonts:
        - asset: assets/fonts/Urbanist-SemiBold.ttf
    - family: Urbanist-Thin
      fonts:
        - asset: assets/fonts/Urbanist-Thin.ttf

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/audio/
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/driver_logo.png"


  
